version: '2.3'

networks:
  back:
    driver: bridge

services:
  db:
    restart: always
    image: mariadb
    cpu_count: 2
    cpu_percent: 50
    mem_limit: 1gb
    memswap_limit: 2gb
    mem_reservation: 512m
    volumes:
      - /data/docker/observium/data/mysql:/var/lib/mysql
    env_file:
      - system.env
      - mysql.env
    networks:
      back:
        aliases:
          - observ_db
  web:
    restart: always
    image: blackojack/observium-ce
    cpu_count: 2
    cpu_percent: 80
    mem_limit: 1gb
    memswap_limit: 2gb
    mem_reservation: 512m
    ports:
      - 8080:80
      - 514:514/udp
    depends_on:
      - db
    volumes:
      - /data/docker/observium/data/rrd:/opt/observium/rrd
      - /data/docker/observium/data/logs:/opt/observium/logs
      - /data/docker/observium/data/html:/opt/observium/html
      - /data/docker/observium/data/mibs:/opt/observium/mibs
      - /data/docker/observium/data/scripts:/opt/observium/scripts
      - /data/docker/observium/data/ssh_keys:/home/rancid/.ssh
      - /data/docker/observium/data/rancid_configs:/usr/local/rancid/var/observium/configs
      - /data/docker/observium/data/rancid_logs:/usr/local/rancid/var/logs
    env_file:
      - system.env
      - mysql.env
      - observium.env
    networks:
      - back
